const { supabaseUrl, supabaseKey } = window.AGENDA_CONFIG;
const db = window.supabase.createClient(supabaseUrl, supabaseKey);
const state = {events:[],categories:[],news:[],category:'todos',period:'all',query:'',favorites:new Set(JSON.parse(localStorage.getItem('derole:favorites')||localStorage.getItem('agendaTL:favorites')||'[]'))};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=(s='')=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmtDate=new Intl.DateTimeFormat('pt-BR',{weekday:'short',day:'2-digit',month:'long'}),fmtDay=new Intl.DateTimeFormat('pt-BR',{day:'2-digit'}),fmtMonth=new Intl.DateTimeFormat('pt-BR',{month:'short'}),fmtTime=new Intl.DateTimeFormat('pt-BR',{hour:'2-digit',minute:'2-digit'}),fmtNewsDate=new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'});
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),2300)}
function eventDate(e){return new Date(e.start_at)} function categoryName(e){return e.categories?.name||'Evento'} function categorySlug(e){return e.categories?.slug||'outros'} function organizerName(e){return e.organizers?.name||'Organizador'}
function priceLabel(e){if(e.is_free)return'Grátis';if(e.price_min!=null&&e.price_max!=null&&e.price_min!==e.price_max)return `R$ ${Number(e.price_min).toFixed(2).replace('.',',')} – R$ ${Number(e.price_max).toFixed(2).replace('.',',')}`;if(e.price_min!=null)return `R$ ${Number(e.price_min).toFixed(2).replace('.',',')}`;return'Consultar'}
function coverClass(slug){return String(slug||'outros').replace(/[^a-z0-9-]/gi,'').toLowerCase()} function isToday(d){const n=new Date();return d.getFullYear()===n.getFullYear()&&d.getMonth()===n.getMonth()&&d.getDate()===n.getDate()}
function isThisWeekend(d){const now=new Date(),daysToSat=(6-now.getDay()+7)%7,sat=new Date(now);sat.setDate(now.getDate()+daysToSat);sat.setHours(0,0,0,0);const sun=new Date(sat);sun.setDate(sat.getDate()+1);sun.setHours(23,59,59,999);return d>=sat&&d<=sun}
async function loadCategories(){const{data,error}=await db.from('categories').select('id,slug,name,icon,sort_order').eq('active',true).order('sort_order');if(error){console.error(error);return}state.categories=data||[];renderCategories();$('#categorySelect').innerHTML=state.categories.map(c=>`<option value="${esc(c.slug)}">${esc(c.name)}</option>`).join('')}
async function loadEvents(){const from=new Date();from.setHours(0,0,0,0);const{data,error}=await db.from('events').select('id,title,slug,summary,description,start_at,end_at,venue_name,address,neighborhood,city,state,cover_url,ticket_url,instagram_url,price_min,price_max,is_free,age_rating,featured,categories(name,slug,icon),organizers(name,instagram_url,whatsapp,website_url)').eq('status','approved').gte('start_at',from.toISOString()).order('start_at',{ascending:true});if(error){console.error(error);$('#eventCount').textContent='Não foi possível carregar';toast('Erro ao carregar a agenda');return}state.events=data||[];render()}
async function loadNews(){const{data,error}=await db.from('news_items').select('id,source_name,source_homepage,title,url,excerpt,image_url,published_at,fetched_at').eq('is_visible',true).order('published_at',{ascending:false,nullsFirst:false}).limit(12);if(error){console.error(error);$('#newsCount').textContent='Radar indisponível';return}state.news=data||[];renderNews()}
function validNewsImage(url){return !!url&&/\.(jpe?g|png|webp|gif)(\?|$)/i.test(url)}
function renderNews(){const grid=$('#newsGrid'),empty=$('#newsEmpty');if(!grid)return;const items=state.news;$('#newsCount').textContent=items.length?`${items.length} manchetes recentes`:'Sem manchetes';empty.hidden=items.length>0;grid.innerHTML=items.map(n=>{const d=n.published_at?new Date(n.published_at):new Date(n.fetched_at),img=validNewsImage(n.image_url)?n.image_url:null,excerpt=(n.excerpt||'').slice(0,170);return `<a class="news-card" href="${esc(n.url)}" target="_blank" rel="noopener noreferrer"><div class="news-media ${img?'has-image':''}" ${img?`style="background-image:url('${esc(img)}')"`:''}><span class="news-source">${esc(n.source_name)}</span>${img?'':'<span class="news-fallback">DR</span>'}</div><div class="news-body"><span class="news-time">${esc(fmtNewsDate.format(d))}</span><h3>${esc(n.title)}</h3>${excerpt?`<p>${esc(excerpt)}${n.excerpt.length>170?'…':''}</p>`:''}<span class="news-link">Ler na fonte ↗</span></div></a>`}).join('')}
function renderCategories(){const cats=[{slug:'todos',name:'Todos',icon:'✦'},...state.categories];$('#categoryGrid').innerHTML=cats.map(c=>`<button class="cat ${state.category===c.slug?'active':''}" data-category="${esc(c.slug)}"><span>${esc(c.icon||'•')}</span><b>${esc(c.name)}</b></button>`).join('')}
function filteredEvents(){let list=[...state.events];if(state.category!=='todos')list=list.filter(e=>categorySlug(e)===state.category);if(state.period==='free')list=list.filter(e=>e.is_free);if(state.period==='today')list=list.filter(e=>isToday(eventDate(e)));if(state.period==='weekend')list=list.filter(e=>isThisWeekend(eventDate(e)));if(state.query){const q=state.query.toLowerCase();list=list.filter(e=>[e.title,e.venue_name,e.city,categoryName(e),organizerName(e)].join(' ').toLowerCase().includes(q))}return list}
function renderFeatured(){const event=state.events.find(e=>e.featured)||state.events[0];if(!event){$('#featuredSection').hidden=true;return}$('#featuredSection').hidden=false;const d=eventDate(event);$('#featuredCard').innerHTML=`<div class="featured-content"><span class="featured-badge">Rolê em destaque</span><h3>${esc(event.title)}</h3><div class="featured-meta"><span>◷ ${esc(fmtDate.format(d))} • ${esc(fmtTime.format(d))}</span><span>⌖ ${esc(event.venue_name)}</span><span>◎ ${esc(priceLabel(event))}</span></div><button class="btn btn-light" data-event-id="${event.id}">Bora ver →</button></div>`}
function renderEvents(){const list=filteredEvents();$('#eventCount').textContent=`${list.length} ${list.length===1?'evento':'eventos'}`;$('#eventsGrid').innerHTML=list.map(e=>{const d=eventDate(e),saved=state.favorites.has(e.id),icon=e.categories?.icon||'✦';return`<article class="event-card" data-event-id="${e.id}"><div class="cover ${coverClass(categorySlug(e))}" ${e.cover_url?`style="background-image:linear-gradient(180deg,rgba(0,0,0,.08),rgba(0,0,0,.62)),url('${esc(e.cover_url)}');background-size:cover;background-position:center"`:''}><span class="cover-cat">${esc(categoryName(e))}</span><button class="save-btn ${saved?'saved':''}" data-save="${e.id}" aria-label="Salvar">${saved?'♥':'♡'}</button>${e.cover_url?'':`<span class="cover-art">${esc(icon)}</span>`}</div><div class="event-body"><div class="datebox"><b>${esc(fmtMonth.format(d).replace('.','').toUpperCase())}</b><strong>${esc(fmtDay.format(d))}</strong></div><div class="event-info"><h3>${esc(e.title)}</h3><p>◷ ${esc(fmtTime.format(d))} · ${esc(e.venue_name)}</p><p>⌖ ${esc(e.city||'Três Lagoas')}/${esc(e.state||'MS')}</p><span class="price ${e.is_free?'free':''}">${esc(priceLabel(e))}</span></div></div></article>`}).join('');$('#emptyState').hidden=list.length>0}
function render(){renderFeatured();renderEvents()}
function openEvent(id){const e=state.events.find(x=>x.id===id);if(!e)return;const d=eventDate(e),shareUrl=`${location.origin}${location.pathname}#evento-${e.slug||e.id}`;$('#eventDialogContent').innerHTML=`${e.cover_url?`<div class="dialog-cover" style="background-image:linear-gradient(180deg,rgba(0,0,0,.06),rgba(0,0,0,.62)),url('${esc(e.cover_url)}');background-size:cover;background-position:center"></div>`:'<div class="dialog-cover"></div>'}<div class="dialog-content"><span class="eyebrow">${esc(categoryName(e).toUpperCase())}</span><h2>${esc(e.title)}</h2><div class="dialog-meta"><div class="meta-box"><small>Data e horário</small><b>${esc(fmtDate.format(d))} • ${esc(fmtTime.format(d))}</b></div><div class="meta-box"><small>Entrada</small><b>${esc(priceLabel(e))}</b></div><div class="meta-box"><small>Local</small><b>${esc(e.venue_name)}</b></div><div class="meta-box"><small>Realização</small><b>${esc(organizerName(e))}</b></div></div><p class="dialog-description">${esc(e.description||e.summary||'Mais informações em breve.')}</p><div class="dialog-actions"><button class="btn btn-dark" data-share="${e.id}" data-url="${esc(shareUrl)}">Compartilhar</button><button class="btn" data-save="${e.id}">${state.favorites.has(e.id)?'♥ Salvo':'♡ Salvar'}</button>${e.ticket_url?`<a class="btn" href="${esc(e.ticket_url)}" target="_blank" rel="noopener">Ingressos ↗</a>`:''}</div></div>`;$('#eventDialog').showModal()}
function saveEvent(id){state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);localStorage.setItem('derole:favorites',JSON.stringify([...state.favorites]));renderEvents();toast(state.favorites.has(id)?'Rolê salvo':'Removido dos salvos')}
async function submitEvent(form){const btn=form.querySelector('button[type="submit"]'),old=btn.textContent;btn.disabled=true;btn.textContent='Enviando…';try{const data=Object.fromEntries(new FormData(form));const payload={title:data.title.trim(),event_date:data.date,event_time:data.time||null,venue_name:data.venue.trim(),address:data.address?.trim()||null,category_slug:data.category,is_free:data.priceType==='free',price_text:data.price?.trim()||null,description:data.description.trim(),contact:data.contact?.trim()||null,organizer_name:data.organizer.trim()};const{error}=await db.from('event_submissions').insert(payload);if(error)throw error;form.reset();$('#submitDialog').close();toast('Rolê enviado pra análise ✓')}catch(err){console.error(err);toast('Não foi possível enviar. Confira os dados.')}finally{btn.disabled=false;btn.textContent=old}}
document.addEventListener('click',e=>{const cat=e.target.closest('.cat');if(cat){state.category=cat.dataset.category;renderCategories();renderEvents();return}const open=e.target.closest('[data-open-submit]');if(open){$('#submitDialog').showModal();return}const close=e.target.closest('[data-close-dialog]');if(close){close.closest('dialog').close();return}const save=e.target.closest('[data-save]');if(save){e.stopPropagation();saveEvent(save.dataset.save);if($('#eventDialog').open)openEvent(save.dataset.save);return}const card=e.target.closest('[data-event-id]');if(card){openEvent(card.dataset.eventId);return}const share=e.target.closest('[data-share]');if(share){const ev=state.events.find(x=>x.id===share.dataset.share);if(!ev)return;const d=eventDate(ev),txt=`${ev.title} — ${fmtDate.format(d)} às ${fmtTime.format(d)}, ${ev.venue_name}, Três Lagoas/MS.`;if(navigator.share)navigator.share({title:ev.title,text:txt,url:share.dataset.url});else navigator.clipboard?.writeText(`${txt} ${share.dataset.url}`).then(()=>toast('Informações copiadas'));return}if(e.target.matches('[data-scroll-events]'))$('#agenda').scrollIntoView({behavior:'smooth'})});
$$('.quick').forEach(b=>b.addEventListener('click',()=>{$$('.quick').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.period=b.dataset.period;renderEvents()}));$('#searchInput').addEventListener('input',e=>{state.query=e.target.value.trim();renderEvents()});$('#clearSearch').addEventListener('click',()=>{$('#searchInput').value='';state.query='';renderEvents()});$('#searchToggle').addEventListener('click',()=>$('#searchInput').focus());$('#favoritesBtn').addEventListener('click',()=>{state.query='';state.category='todos';state.period='all';renderCategories();const ids=state.favorites,list=state.events.filter(e=>ids.has(e.id));$('#eventsGrid').innerHTML='';if(!list.length){$('#emptyState').hidden=false;$('#eventCount').textContent='0 salvos';toast('Você ainda não salvou rolês');return}const prev=state.events;state.events=list;renderEvents();state.events=prev;$('#eventCount').textContent=`${ids.size} salvos`});$('#submitForm').addEventListener('submit',e=>{e.preventDefault();submitEvent(e.currentTarget)});$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d)d.close()}));Promise.all([loadCategories(),loadEvents(),loadNews()]).catch(console.error);if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));